### ISSUE TITLE
gradle build fails

### ISSUE THREAD

**Issue by WolfgangFahl** [kaklakariada/fritzbox-java-api#1]
./gradlew clean install

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'fritzbox-java-api'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by WolfgangFahl** [comment]
see https://github.com/kaklakariada/fritzbox-java-api/pull/2 for  a working maven pom.xml

**Comment by kaklakariada** [comment]
The instructions in readme where wrong. I updated them. Please use this command:
```
./gradlew clean publishToMavenLocal
```

**Comment by WolfgangFahl** [comment]
I am using a maven based eclipse environment. Gradle is not useful in my environment.
