### ISSUE TITLE
Device.battery and Device.batteryLow: Make 'undefined' detectable

### ISSUE THREAD

**Issue by philippn** [kaklakariada/fritzbox-java-api#11]
Hi there,
I have another suggestion to make regarding your API. In the Device class, `battery` and `batteryLow` are currently mapped as `int`. This yields the problem that it is indistinguishable whether the value is 0 or not set at all.

Basically, I see two options here to circumvent this problem:
- map the field to an `Integer` instead, in that case `null` would mean that it is not set
- set the default value of these fields to `-1`, which clients could handle specifically

Thanks again for your nice work and kind regards,
Philipp

**Comment by philippn** [comment]
Please find attached sample Devicelist of a Fritz DECT switch 200 (without battery) and screenshot from code
[fritz-dect.zip](https://github.com/kaklakariada/fritzbox-java-api/files/3914785/fritz-dect.zip)
![battery-batterylow](https://user-images.githubusercontent.com/445105/70023251-1bddff00-1597-11ea-8d71-a1cf5cab479e.png)

**Comment by kaklakariada** [comment]
Hi @philippn 
is this what you want: https://github.com/kaklakariada/fritzbox-java-api/pull/12/files#diff-08a9d6a4121e714a8a702a9d5595c483 ? If yes I will include this into a new release.

**Comment by philippn** [comment]
Hi @kaklakariada, yes, exactly 👍

**Comment by kaklakariada** [comment]
This is a breaking change, that's why I incremented the version to 1.0.0.
You can now download it now from the jcenter maven repo.
