### ISSUE TITLE
Support for device "Blind" and device-attribute "Alert" missing

### ISSUE THREAD

**Issue by JunkerMartin** [kaklakariada/fritzbox-java-api#30]
Fritz@Box supports blinds. Does it for longer, but in Fritz!OS 7.29 it is even mentioned in the upgrade docs.

**Comment by TDesjardins** [comment]
@JunkerMartin Seems this is also fixed: https://github.com/kaklakariada/fritzbox-java-api/blob/141f563b492a1265c3d25dde006cbdeba978b091/src/main/java/com/github/kaklakariada/fritzbox/model/homeautomation/Device.java#L77

**Comment by kaklakariada** [comment]
Seems to be fixed. If there is a problem, please create another ticket.
