### ISSUE TITLE
Statistics retrieval is not working

### ISSUE THREAD

**Issue by JunkerMartin** [kaklakariada/fritzbox-java-api#33]
The retrieval of statistics with "EnergyStatisticsService" does not work. I think, this is why the call to the service is made as a comment in "TestDriver". Reason for this error, as far as I understand it, is a wrong command "command".
I have added retrieval of statistics with command ""switchcmd","getbasicdevicestats" to my local copy of the code and added the call also to "TestDriver". I didn't want to update (and am not allowed to, anyway) the  kaklakariada-reporsitory, so I uploaded the changed code to my reporsitory. Can be found at https://github.com/JunkerMartin/fritzbox-java-api

**Comment by TDesjardins** [comment]
I wonder if this is fixed with: https://github.com/kaklakariada/fritzbox-java-api/commit/2c50db646931341164ca54e44266cbe78811f79e  ?

**Comment by JunkerMartin** [comment]
Yes, this should be fixed. I checked the code in your repository - it matches what I uploaded

**Comment by kaklakariada** [comment]
@JunkerMartin great, thank you for checking that!
