### ISSUE TITLE
Reading objects from inputstream

### ISSUE THREAD

**Issue by TDesjardins** [kaklakariada/fritzbox-java-api#53]
Currently the deserializer reads a string build from the reponse body:

https://github.com/kaklakariada/fritzbox-java-api/blob/master/src/main/java/com/github/kaklakariada/fritzbox/mapping/Deserializer.java#L41

okhttp and simple-xml both support streaming so reading an object can be made more efficient especially for larger objects.

I could provide a PR if this feature is wanted.

**Comment by kaklakariada** [comment]
Good idea, a pr is welcome 😁
