### ISSUE TITLE
Cannot connect to FritzBox

### ISSUE THREAD

**Issue by hwacookie** [kaklakariada/fritzbox-java-api#6]
I cannot connect to my fritzBox. I've set the correct values in the application.properties, but I keep getting "com.github.kaklakariada.fritzbox.LoginFailedException: Login failed, blocked for ..." messages.
I double checked, I can connect via the FritBox Gui with these credentials without problems.
I might be using it wrong - any ideas what I could try?
I know it used to work properly some time ago with an earlier version of your API - unfortunatly, I canno remember which one that was.

**Comment by kaklakariada** [comment]
Hi @hwacookie , Which version of FRITZ!OS do you use? Login works for me with version 06.92.
If don't use a user account you could try to create a user and specify the user name. Maybe login without a user does not work any more with newer versions of FRITZ!OS.

**Comment by kaklakariada** [comment]
No feedback, I will close this ticket.
